# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PinkBook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PinkBook
  pod 'XLPagerTabStrip', '~> 9.0'
  pod 'CHTCollectionViewWaterfallLayout/Swift'
  pod 'YPImagePicker'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'SKPhotoBrowser'
  pod 'KMPlaceholderTextView', '~> 1.4.0'
  pod 'AMapLocation'
  pod 'AMapSearch'
  pod 'MJRefresh'
  pod 'DateToolsSwift'
  pod 'JVerification'
  
end

#post_install do |installer|
#  installer.pods_project.build_configurations.each do |config|
#    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#  end
#end
